version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.9
    commands:
      - echo -e '@neverendingsupport:registry=https://registry.nes.herodevs.com/npm/pkg/\n//registry.nes.herodevs.com/npm/pkg/:_authToken="'${NES_AUTH_TOKEN}'"' > .npmrc
      - cat .npmrc
      - npm -v
      - npm install
      - npm install -g typescript@4.7.4

  pre_build:
    commands:
      - echo "pre_build phase"

  build:
    commands:
      - npm run build-vue
      - tsc --resolveJsonModule --esModuleInterop ./scripts/node_js/save_whiteboard_as_png.ts

  post_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/create-build-summary.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - '.platform/**/*'
  - 'Procfile'
  - 'application.py'
  - 'app/**/*'
  - 'config/**/*'
  - 'consoler.py'
  - 'dist/**/*'
  - 'fixtures/**/*'
  - 'node_modules/**/*'
  - 'requirements.txt'
  - 'scripts/**/*'
  - 'squiggy/**/*'
