version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - npm -v
      - npm install
      - npm install -g typescript

  pre_build:
    commands:
      - echo "pre_build phase"

  build:
    commands:
      - npm install -g n
      - n latest
      - npm update -g npm
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - npm install -g @vue/cli
      - npm run build-vue
      - tsc --resolveJsonModule --esModuleInterop ./scripts/node_js/save_whiteboard_as_png.ts

  post_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/create-build-summary.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - '.platform/**/*'
  - 'application.py'
  - 'app/**/*'
  - 'config/**/*'
  - 'consoler.py'
  - 'dist/**/*'
  - 'fixtures/**/*'
  - 'node_modules/**/*'
  - 'requirements.txt'
  - 'scripts/**/*'
  - 'squiggy/**/*'
